### ISSUE TITLE
Create customTask - CSS Uglify

### ISSUE THREAD

**Issue by SAPMarco** [SAPMarco/github_pages#20]
Maybe I can create a custom task in order to uglify my custom CSS?

https://github.com/SAP/ui5-cli/issues/192

```yaml
specVersion: "1.0"
kind: project
type: application
metadata:
  name: openui5-sample-app
builder:
  customTasks:
  - name: demoTask
    afterTask: uglify
    configuration:
      color: blue
---
# Task extension as part of your project
specVersion: "1.0"
kind: extension
type: task
metadata:
  name: demoTask
task:
  path: tasks/demoTask.js
```

create folder tasks in the project root on the same level as webapp
create the demo task in the task folder
```js
module.exports = async function({workspace, dependencies, options}) {
	console.log(workspace,dependencies,options)
};
```

https://sap.github.io/ui5-tooling/api/module-@ui5_builder.tasks.html#.uglify
